name: Build Full Blender Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Blender Fork
      uses: actions/checkout@v4
      with:
        repository: yashgore/blender  # ✅ Replace with your GitHub fork
        fetch-depth: 1

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git cmake ninja-build \
          python3-dev zip wget pkg-config openjdk-17-jdk \
          libx11-dev libxi-dev libgl1-mesa-dev \
          libxcursor-dev libxrandr-dev libxinerama-dev libxxf86vm-dev

    - name: Setup Android SDK/NDK
      uses: android-actions/setup-android@v3
      with:
        sdk-version: 34
        ndk-version: 25.2.9519653

    - name: Clone Full Blender with LFS and Submodules
      run: |
        git lfs install
        git clone https://github.com/yashgore/blender.git
        cd blender
        git submodule update --init --recursive

    - name: Configure Full Blender for Android (Java + C++ + Python)
      run: |
        cd blender
        mkdir build-android && cd build-android
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-24 \
          -DCMAKE_BUILD_TYPE=Debug \
          -DWITH_PYTHON=ON \
          -DWITH_CYCLES=ON \
          -DWITH_EEVEE=ON \
          -DWITH_COMPOSITOR=ON \
          -DWITH_SCULPT_MODE=ON \
          -DWITH_VSE=ON \
          -DWITH_SIMULATION=ON \
          -DWITH_MOD_FLUID=ON \
          -DWITH_IMAGE_WEBP=ON \
          -DWITH_OPENVDB=ON \
          -DWITH_OPENCOLLADA=ON \
          -DWITH_GHOST_X11=OFF \
          -DWITH_GHOST_SDL=ON \
          -DWITH_INSTALL_PORTABLE=ON

    - name: Build Blender APK
      run: |
        cd blender/build-android
        make -j$(nproc)

    - name: Upload Full APK
      uses: actions/upload-artifact@v4
      with:
        name: full-blender-apk
        path: blender/build-android/bin/*.apk
