name: Build Full Blender Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git cmake ninja-build wget unzip zip \
          python3-dev pkg-config openjdk-17-jdk \
          libx11-dev libxi-dev libgl1-mesa-dev \
          libxcursor-dev libxrandr-dev libxinerama-dev libxxf86vm-dev

    - name: Setup Android SDK & NDK
      uses: android-actions/setup-android@v3
      with:
        sdk-version: 34
        ndk-version: 25.2.9519653

    - name: Clone Official Blender Repo (Skip broken LFS)
      run: |
        git clone https://github.com/blender/blender.git
        cd blender
        git lfs install
        GIT_LFS_SKIP_SMUDGE=1 git lfs pull
        git submodule update --init --recursive

    - name: Configure Full Android Build (with C++/Java/Python)
      run: |
        cd blender
        mkdir -p build-android
        cd build-android

        cmake .. \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-24 \
          -DWITH_PYTHON=ON \
          -DWITH_CYCLES=ON \
          -DWITH_EEVEE=ON \
          -DWITH_COMPOSITOR=ON \
          -DWITH_SCULPT_MODE=ON \
          -DWITH_VSE=ON \
          -DWITH_SIMULATION=ON \
          -DWITH_MOD_FLUID=ON \
          -DWITH_IMAGE_WEBP=ON \
          -DWITH_OPENVDB=ON \
          -DWITH_OPENCOLLADA=ON \
          -DWITH_GHOST_X11=OFF \
          -DWITH_GHOST_SDL=ON \
          -DWITH_INSTALL_PORTABLE=ON

    - name: Build Blender
      run: |
        cd blender/build-android
        ninja

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: blender-full-android-apk
        path: blender/build-android/bin/*.apk
