name: Build Blender Android APK (Modeling Only)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Blender
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git cmake ninja-build python3 zip wget pkg-config openjdk-17-jdk

    - name: Setup Android SDK + NDK
      uses: android-actions/setup-android@v3
      with:
        sdk-version: 33
        ndk-version: 25.2.9519653

    - name: Clone Blender
      run: |
        git clone https://github.com/blender/blender.git
        cd blender
        git submodule update --init --recursive

    - name: Configure CMake (Modeling Only)
      run: |
        cd blender
        mkdir build-android && cd build-android
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-24 \
          -DCMAKE_BUILD_TYPE=Release \
          -DWITH_PYTHON=OFF \
          -DWITH_CYCLES=OFF \
          -DWITH_VSE=OFF \
          -DWITH_COMPOSITOR=OFF \
          -DWITH_SCULPT_MODE=OFF \
          -DWITH_MOD_FLUID=OFF \
          -DWITH_IMAGE_WEBP=OFF \
          -DWITH_OPENVDB=OFF \
          -DWITH_GHOST_SDL=ON \
          -DWITH_GHOST_X11=OFF

    - name: Build Blender
      run: |
        cd blender/build-android
        make -j$(nproc)

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: blender-modeling-apk
        path: blender/build-android/bin/*.apk
