name: Heavy Debug Build - Blender Android Modeling APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Your Fork
      uses: actions/checkout@v4
      with:
        repository: your-username/blender  # <-- Replace with your forked repo!
        fetch-depth: 1

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git cmake ninja-build python3-dev zip wget pkg-config openjdk-17-jdk

    - name: Set Up Android SDK + NDK
      uses: android-actions/setup-android@v3
      with:
        sdk-version: 34
        ndk-version: 25.2.9519653

    - name: Configure Blender Android Build (Debug + Modeling Only)
      run: |
        cd blender
        mkdir build-android && cd build-android
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-24 \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_C_FLAGS_DEBUG="-O0 -g3 -Wall -fstack-protector-all" \
          -DCMAKE_CXX_FLAGS_DEBUG="-O0 -g3 -Wall -fstack-protector-all" \
          -DWITH_PYTHON=OFF \
          -DWITH_SCULPT_MODE=OFF \
          -DWITH_SIMULATION=OFF \
          -DWITH_VSE=OFF \
          -DWITH_COMPOSITOR=OFF \
          -DWITH_IMAGE_WEBP=OFF \
          -DWITH_MOD_FLUID=OFF \
          -DWITH_CYCLES=OFF \
          -DWITH_OPENVDB=OFF \
          -DWITH_OPENCOLLADA=OFF \
          -DWITH_GHOST_X11=OFF \
          -DWITH_GHOST_SDL=ON

    - name: Build Blender (Debug Mode)
      run: |
        cd blender/build-android
        make -j$(nproc) VERBOSE=1

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: blender-modeling-debug-apk
        path: blender/build-android/bin/*.apk
